[google]
GOOGLE_API_KEY="AIzaSyA-DbnvKVfVC9lqR_os0wnTf0f8r-BCau4"

[supabase]
SUPABASE_URL="https://jixqcprxeaaxbherydsl.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppeHFjcHJ4ZWFheGJoZXJ5ZHNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0Njc5NDIsImV4cCI6MjA2MTA0Mzk0Mn0.ua81rJ4d7od6JJXbdQ2q5uZf-3LittS3Lw4razHGS0E"
